package model;
// Generated 11/03/2018 02:52:05 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Alumno generated by hbm2java
 */
public class Alumno  implements java.io.Serializable {


     private Integer matricula;
     private String grupo;
     private String nombre;
     private String apaterno;
     private String amaterno;
     private Integer telefono;
     private String email;
     private Integer edad;
     private String sexo;
     private Set<Asignaturas> asignaturases = new HashSet<Asignaturas>(0);

    public Alumno() {
    }

    public Alumno(String grupo, String nombre, String apaterno, String amaterno, Integer telefono, String email, Integer edad, String sexo, Set<Asignaturas> asignaturases) {
       this.grupo = grupo;
       this.nombre = nombre;
       this.apaterno = apaterno;
       this.amaterno = amaterno;
       this.telefono = telefono;
       this.email = email;
       this.edad = edad;
       this.sexo = sexo;
       this.asignaturases = asignaturases;
    }
   
    public Integer getMatricula() {
        return this.matricula;
    }
    
    public void setMatricula(Integer matricula) {
        this.matricula = matricula;
    }
    public String getGrupo() {
        return this.grupo;
    }
    
    public void setGrupo(String grupo) {
        this.grupo = grupo;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getApaterno() {
        return this.apaterno;
    }
    
    public void setApaterno(String apaterno) {
        this.apaterno = apaterno;
    }
    public String getAmaterno() {
        return this.amaterno;
    }
    
    public void setAmaterno(String amaterno) {
        this.amaterno = amaterno;
    }
    public Integer getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(Integer telefono) {
        this.telefono = telefono;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public Integer getEdad() {
        return this.edad;
    }
    
    public void setEdad(Integer edad) {
        this.edad = edad;
    }
    public String getSexo() {
        return this.sexo;
    }
    
    public void setSexo(String sexo) {
        this.sexo = sexo;
    }
    public Set<Asignaturas> getAsignaturases() {
        return this.asignaturases;
    }
    
    public void setAsignaturases(Set<Asignaturas> asignaturases) {
        this.asignaturases = asignaturases;
    }




}


