package model;
// Generated 11/03/2018 02:52:05 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Profesor generated by hbm2java
 */
public class Profesor  implements java.io.Serializable {


     private Integer idprofesor;
     private String nombre;
     private String apaterno;
     private String amaterno;
     private String direccion;
     private Integer telefono;
     private String email;
     private String sexo;
     private String titulo;
     private Integer cedula;
     private Set<Asignaturas> asignaturases = new HashSet<Asignaturas>(0);

    public Profesor() {
    }

    public Profesor(String nombre, String apaterno, String amaterno, String direccion, Integer telefono, String email, String sexo, String titulo, Integer cedula, Set<Asignaturas> asignaturases) {
       this.nombre = nombre;
       this.apaterno = apaterno;
       this.amaterno = amaterno;
       this.direccion = direccion;
       this.telefono = telefono;
       this.email = email;
       this.sexo = sexo;
       this.titulo = titulo;
       this.cedula = cedula;
       this.asignaturases = asignaturases;
    }
   
    public Integer getIdprofesor() {
        return this.idprofesor;
    }
    
    public void setIdprofesor(Integer idprofesor) {
        this.idprofesor = idprofesor;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getApaterno() {
        return this.apaterno;
    }
    
    public void setApaterno(String apaterno) {
        this.apaterno = apaterno;
    }
    public String getAmaterno() {
        return this.amaterno;
    }
    
    public void setAmaterno(String amaterno) {
        this.amaterno = amaterno;
    }
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }
    public Integer getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(Integer telefono) {
        this.telefono = telefono;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getSexo() {
        return this.sexo;
    }
    
    public void setSexo(String sexo) {
        this.sexo = sexo;
    }
    public String getTitulo() {
        return this.titulo;
    }
    
    public void setTitulo(String titulo) {
        this.titulo = titulo;
    }
    public Integer getCedula() {
        return this.cedula;
    }
    
    public void setCedula(Integer cedula) {
        this.cedula = cedula;
    }
    public Set<Asignaturas> getAsignaturases() {
        return this.asignaturases;
    }
    
    public void setAsignaturases(Set<Asignaturas> asignaturases) {
        this.asignaturases = asignaturases;
    }




}


